main: Quest3\Main3
version: 1.0
api: 
- 1.0.0
- 1.1.0
- 1.2.0
- 1.2.1
- 3.0.0-ALPHA6
- 3.0.0-ALPHA5
- 3.0.0-ALPHA4
- 2.0.0
name: PocketRefill
author: ZASXCV_DEV
commands:
 wallet:
  description: เเจ้งโอนวอเล็ท พิม /wallet [เลขอ้างอิง]
 truemoney:
  description: เติมเงินด้วยบัตร พิม /truemoney [เลขบัตรทรู]
           jssjsjsjjsj
sjsjsjsjss
