#ระบบเติมเงิน Truewallet, บัตรทรู
#จัดทำโดย ZASXCV
#FB : Peerapat Nunat

#อีเมลทรูวอเล็ท
email: email@gmail.com

#รหัสผ่านทรูวอเล็ท
password: 11111111

#คำสั่งเมื่อเเจ้งโอนสำเร็จ เช่น say {player} {amount} 
#หมายเหตุ {player} = ชื่อผู้เล่น , {amount} = จำนวนเงินที่โอน
command: say {player} {amount}

#ชนิดการเก็บข้อมูล รองรับ MYSQL
#MYSQL, SQLITE (ถ้าไม่รู้ห้ามเปลี่ยน)
#สำหรับเช็คว่า เลขอ้างอิงนี้ใช้ไปหรือหยัง
data-type: SQLITE

#เชื่อมต่อฐานข้อมูล (ถ้ามี)
host: localhost
#ผู้ใช้
user: root
#รหัสผ่าน
pass: password
#ฐานข้อมูล
database: pocketrefill
